### ISSUE TITLE
Move repo to nursery?

### ISSUE THREAD

**Issue by saneyuki** [rust-lang-nursery/rls_vscode#23]
I feel this project should be placed in [rust-lang-nursery](https://github.com/rust-lang-nursery) by these reasons:

- [rust-lang](https://github.com/rust-lang) has also an editor integration for others (e.g. rust-mode, rust-vim, sublime-rust).
- rls has same issue: https://github.com/jonathandturner/rls/issues/141

**Comment by nrc** [comment]
Done now
