### ISSUE TITLE
Switch to yarn?

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang-nursery/rls_vscode#34]
Switching to [Yarn](https://yarnpkg.com) would give us a couple easy wins here—builds would be coming both *deterministic* and *much faster*. Not to mention the obvious synergy of using *another* package manager Yehuda helped with, right? :smirk:

Tasks this would entail:

- Update the README to suggest running `yarn` (perhaps with fallback to `npm install`)
- Commit the `yarn.lock` file
- …that's it.

Happy to submit a PR to do those. 😄

**Comment by jonathandturner** [comment]
We just follow the standard VS Code plugin template.  If they switch to yarn, yeah, we should definitely do, too.

**Comment by jonathandturner** [comment]
Just checked again.  Looks like vscode is currently still using `npm` for building its plugins, so I'm going to go ahead and close this.  Please re-open if things change.
